### ISSUE TITLE
order of display for attributes

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/atk#3]
Hello,
I wonder how is defined the order into which the attributes are displayed.
By default, I imagine attributes are displayed in lowercase but in some case of DS we did not developped, we noticed the display order can be otherwise.

I would be interested to know how to change this display order. 
Is there several or a specific way to do this?

Regards.

**Comment by PhilLAL** [comment]
Up to remember this issue, but no urge. :)

**Comment by faranguiss-poncet** [comment]
Dear PhilLAL,
ATK does not do anything about the display order of the attributes.
In fact the atkpanel (device monitoring application) tries to get connected to all so-called "operator" (means not expert) attributes of a device. To get all the attributes of one device here is what is done in ATK source code

- Get the exhaustive list of all the device attributes by calling the JTango method : myDeviceProxy.getAttributeInfo((String[])null);
- This call will return an array  AttributeInfoEx []
- This AttributeInfoEx [] array is explored in the same order which was returned by the JTango method

So the order is defined in the method getAttributeInfo of the class DeviceProxy in JTango not in ATK.

I hope that this answer can help.
Perhaps we can move the issue to the JTango related issues.
Best regards,
Faranguiss

**Comment by PhilLAL** [comment]
Thank you for these explanations.
We encountered a very strange behavior then, we got different order in ATKPanel, it is shown in https://github.com/tango-controls/SimulatorDS/issues/10 

Do you confirm this should be linked to JTango?
Regards

**Comment by faranguiss-poncet** [comment]
Well after discussion with colleagues which are involved in JTango Client API development, it seems that the getAttributeInfo method returns the array of AttributeInfoEx []:

1. In the order they appear in Pogo (this is tested and confirmed for the C++ device servers). Be careful with the dynamic attributes which do not follow this rule.

1. The behavior is not the same if the DeviceProxy is instantiated for a Java device server. The Pogo order does not seem to be the one which is used.

1. For Python Device servers I don't know. Have you tried to see if the order is the one they appear in Pogo (creation order)?? Should be the same behavior that for C++ device servers

Anyway, I think the DeviceProxy method call should return the array of all attributes in the same order no matter the device server is written in C++, Java or Python but apparently this is not the case.

Concerning the other problem you have: the READ-WRITE attributes, appearing READ ONLY the problem does not concern neither ATK nor JTango client library used by ATK. 

As Sergio has already answered you, some weeks ago, it seems to be an issue for PyTango: 
_**_The problem seems to come from PyTango, when I execute DeviceProxy('sys/tg_test/1').get_attribute_config('double_scalar').writable it returns WT_UNKNOWN instead of the expected READ_WRITE that appears in Jive**_

Best regards,
Faranguiss

**Comment by PhilLAL** [comment]
> Well after discussion with colleagues which are involved in JTango Client API development, it seems that the getAttributeInfo method returns the array of AttributeInfoEx []:
> 
>     1. In the order they appear in Pogo (this is tested and confirmed for the C++ device servers). Be careful with the dynamic attributes which do not follow this rule.
> 
>     2. The behavior is not the same if the DeviceProxy is instantiated for a Java device server. The Pogo order does not seem to be the one which is used.
> 
>     3. For Python Device servers I don't know. Have you tried to see if the order is the one they appear in Pogo (creation order)?? Should be the same behavior that for C++ device servers
> 
> Anyway, I think the DeviceProxy method call should return the array of all attributes in the same order no matter the device server is written in C++, Java or Python but apparently this is not the case.

Ok, I understand better. 
This explains the current behavior where the Simulated DS use Python but the PowerSupply is developped in C++.

> Concerning the other problem you have: the READ-WRITE attributes, appearing READ ONLY the problem does not concern neither ATK nor JTango client library used by ATK.
> 
> As Sergio has already answered you, some weeks ago, it seems to be an issue for PyTango:
> _**_The problem seems to come from PyTango, when I execute DeviceProxy('sys/tg_test/1').get_attribute_config('double_scalar').writable it returns WT_UNKNOWN instead of the expected READ_WRITE that appears in Jive**_

Sorry, I was not waiting some answer from youon this topic since Sergi was very clear about the origin.

Anyway, thank you for your enlighting answer Faranguiss. :)
